abbreviations_dict = {
    "b.e": "bachelor of engineering",
    "b.tech": "bachelor of technology",
    "m.e": "master of engineering",
    "m.tech": "master of technology",
    "bsc": "bachelor of science",
    "b.sc": "bachelor of science",
    "ba": "bachelor of arts",
    "b.a": "bachelor of arts",
    "m.sc": "master of science",
    "msc": "master of science",
    "m.a": "master of arts",
    "ma": "master of arts",
    "mba": "master of business administration",
    "phd": "doctor of philosophy",
    "bba": "bachelor of business administration",
    "bca": "bachelor of computer applications",
    "mca": "master of computer applications",
    "b.com": "bachelor of commerce",
    "m.com": "master of commerce",
    "b.arch": "bachelor of architecture",
    "m.arch": "master of architecture",
    "bds": "bachelor of dental surgery",
    "mbbs": "bachelor of medicine, bachelor of surgery",
    "md": "doctor of medicine",
    "ms": "master of surgery",
    "bpharm": "bachelor of pharmacy",
    "mpharm": "master of pharmacy",
    "bpt": "bachelor of physiotherapy",
    "mpt": "master of physiotherapy",
    "bhms": "bachelor of homeopathic medicine and surgery",
    "bams": "bachelor of ayurvedic medicine and surgery",
    "b.ed": "bachelor of education",
    "m.ed": "master of education",
    "llb": "bachelor of laws",
    "llm": "master of laws",
    "dba": "doctor of business administration",
    "dsc": "doctor of science",
    "dpharm": "diploma in pharmacy",
    "pgdm": "post graduate diploma in management",
    "bfa": "bachelor of fine arts",
    "mfa": "master of fine arts",
    "b.lib": "bachelor of library science",
    "m.lib": "master of library science",
    "bmm": "bachelor of mass media",
    "bjmc": "bachelor of journalism and mass communication",
    "mjmc": "master of journalism and mass communication",
    "mphil": "master of philosophy",
    "d.phil": "doctor of philosophy",
    "dm": "doctorate of medicine",
    "mch": "master of chirurgical",
    "dpt": "doctor of physical therapy",
    "dds": "doctor of dental surgery",
    "dmd": "doctor of medicine in dentistry",
    "od": "doctor of optometry",
    "dvm": "doctor of veterinary medicine",
    "dc": "doctor of chiropractic",
    "psyd": "doctor of psychology",
    "jd": "juris doctor",
    "ed.d": "doctor of education",
    "th.d": "doctor of theology",
    "cse": "Computer Science Engineering",
    "it": "Information Technology",
    "ece": "Electronics and Communication Engineering",
    "eee": "Electrical and Electronics Engineering",
    "me": "Mechanical Engineering",
    "ce": "Civil Engineering",
    "che": "Chemical Engineering",
    "bme": "Biomedical Engineering",
    "ae": "Aerospace Engineering",
    "auto": "Automobile Engineering",
    "ra": "Robotics & Automation",
    "dsai": "Data Science and Artificial Intelligence",
    "se": "Software Engineering",
    "ipe": "Industrial and Production Engineering",
    "env": "Environmental Engineering",
    "mt": "Metallurgical Engineering",
    "mining": "Mining Engineering",
    "mechatronics": "Mechatronics Engineering",
    "petroleum": "Petroleum Engineering",
    "marine": "Marine Engineering",
    "textile": "Textile Engineering",
    "agri": "Agricultural Engineering",
    "nano": "Nanotechnology Engineering"
}
